services:
  nginx:
    container_name: studytracker.nginx
    image: "nginx:1.29.1"
    expose:
      - "80"
    ports:
      - "127.0.0.1:80:80"
    networks:
      - studytracker.postgres.Network
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api

  api:
    container_name: studytracker.api
    build:
      context: .
    expose:
      - "5000"
    restart: "unless-stopped"
    env_file:
      - "./config/.env"
    volumes:
      - "./config/config.toml:/app/config.toml:ro"
    command: studytracker-server
    depends_on:
      - migrations
  
  migrations:
    container_name: studytracker.migrations
    build:
      context: .
    env_file:
      - "./config/.env"
    volumes:
      - "./config/config.toml:/app/config.toml:ro"
    command: alembic upgrade head
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    container_name: studytracker.postgres
    image: "postgres:17-alpine"
    expose:
      - "5432"
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - studytracker.postgres.data:/var/lib/postgresql/data/:rw
    networks:
      - studytracker.postgres.Network
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=studytracker_db
    logging:
      options:
        max-size: "50m"
    restart: "unless-stopped"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d studytracker_db -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 40s

volumes:
  studytracker.postgres.data: {}

networks:
  studytracker.postgres.Network: {}
